"""
Complete test suite for cortex script generator
"""

from pathlib import Path

import pytest

from cortex.script_gen import STACK_DEPS, ScriptGenerator


class TestScriptGenerator:
    """Test suite for ScriptGenerator class"""

    @pytest.fixture
    def generator(self):
        """Create ScriptGenerator instance for each test"""
        return ScriptGenerator()

    @pytest.fixture
    def temp_script(self, tmp_path):
        """Create temporary script file"""
        script_file = tmp_path / "test_script.sh"
        return script_file

    # ===== GENERATION TESTS =====

    def test_generate_docker_bash(self, generator, temp_script):
        generator.generate(str(temp_script), stack="docker", format="bash")
        assert temp_script.exists()
        content = temp_script.read_text()
        assert "#!/bin/bash" in content
        assert "docker.io" in content
        assert "docker-compose" in content
        assert "set -euo pipefail" in content

    def test_generate_python_bash(self, generator, temp_script):
        generator.generate(str(temp_script), stack="python", format="bash")
        assert temp_script.exists()
        content = temp_script.read_text()
        assert "python3" in content
        assert "python3 --version" in content

    def test_generate_nodejs_bash(self, generator, temp_script):
        generator.generate(str(temp_script), stack="nodejs", format="bash")
        assert temp_script.exists()
        content = temp_script.read_text()
        assert "nodejs" in content
        assert "npm" in content

    def test_generate_ollama_bash(self, generator, temp_script):
        generator.generate(str(temp_script), stack="ollama", format="bash")
        assert temp_script.exists()
        content = temp_script.read_text()
        assert "ollama" in content

    def test_generate_docker_ansible(self, generator, temp_script):
        generator.generate(str(temp_script), stack="docker", format="ansible")
        assert temp_script.exists()
        content = temp_script.read_text()
        assert "---" in content
        assert "name: Install docker" in content
        assert "docker.io" in content
        assert "docker-compose" in content

    def test_generate_python_ansible(self, generator, temp_script):
        generator.generate(str(temp_script), stack="python", format="ansible")
        assert temp_script.exists()
        content = temp_script.read_text()
        assert "---" in content
        assert "python3" in content

    # ===== FILE OPERATIONS =====

    def test_file_is_executable(self, generator, temp_script):
        generator.generate(str(temp_script), stack="docker", format="bash")
        assert temp_script.stat().st_mode & 0o111  # Check execute bit

    def test_file_contains_timestamp(self, generator, temp_script):
        generator.generate(str(temp_script), stack="docker", format="bash")
        content = temp_script.read_text()
        assert "Generated by Cortex Linux" in content
        assert "T" in content  # ISO format timestamp

    def test_dry_run_no_write(self, generator, temp_script):
        generator.generate(str(temp_script), stack="docker", dry_run=True)
        assert not temp_script.exists()

    # ===== ERROR HANDLING =====

    def test_invalid_stack(self, generator, temp_script):
        with pytest.raises(SystemExit):
            generator.generate(str(temp_script), stack="invalid_stack")

    def test_invalid_format(self, generator, temp_script):
        with pytest.raises(SystemExit):
            generator.generate(str(temp_script), stack="docker", format="invalid_format")

    # ===== IDEMPOTENCY TESTS =====
    def test_idempotent_check_docker(self, generator, temp_script):
        generator.generate(str(temp_script), stack="docker")
        content = temp_script.read_text()

        # Check uses 'docker' (check_command), installs 'docker.io' (package)
        assert "command_exists docker" in content
        assert "Installing docker.io" in content
        assert "Installing docker-compose" in content
        assert temp_script.stat().st_mode & 0o111  # executable

    def test_idempotent_check_python(self, generator, temp_script):
        generator.generate(str(temp_script), stack="python")
        content = temp_script.read_text()

        assert "command_exists python3" in content
        assert "Installing python3" in content
        assert temp_script.stat().st_mode & 0o111

    def test_idempotent_check_nodejs(self, generator, temp_script):
        generator.generate(str(temp_script), stack="nodejs")
        content = temp_script.read_text()

        # Check uses 'node' (check_command), installs 'nodejs' (package)
        assert "command_exists node" in content
        assert "Installing nodejs" in content
        assert "Installing npm" in content
        assert temp_script.stat().st_mode & 0o111

    def test_idempotent_check_ollama(self, generator, temp_script):
        generator.generate(str(temp_script), stack="ollama")
        content = temp_script.read_text()

        assert "command_exists ollama" in content
        assert "Installing ollama" in content
        assert temp_script.stat().st_mode & 0o111

    # ===== BASH BEST PRACTICES =====
    def test_strict_mode_bash(self, generator, temp_script):
        generator.generate(str(temp_script), stack="docker")
        content = temp_script.read_text()
        assert "set -euo pipefail" in content

    def test_error_trap_bash(self, generator, temp_script):
        generator.generate(str(temp_script), stack="docker")
        content = temp_script.read_text()
        assert "trap" in content
        assert "log_error" in content

    def test_logging_functions_bash(self, generator, temp_script):
        generator.generate(str(temp_script), stack="docker")
        content = temp_script.read_text()
        assert "log_info()" in content
        assert "log_warn()" in content
        assert "log_error()" in content

    def test_color_codes_bash(self, generator, temp_script):
        generator.generate(str(temp_script), stack="docker")
        content = temp_script.read_text()
        assert "GREEN=" in content
        assert "YELLOW=" in content
        assert "RED=" in content

    # ===== TESTING MODE =====
    def test_syntax_check_valid(self, generator, temp_script):
        generator.generate(str(temp_script), stack="docker")
        # Should not raise exception
        generator.test(str(temp_script), sandbox=True)

    def test_syntax_check_missing_file(self, generator, temp_script):
        with pytest.raises(SystemExit):
            generator.test("non_existent_file.sh")

    # ===== TEMPLATE VERIFICATION =====
    def test_verification_command_docker(self, generator, temp_script):
        generator.generate(str(temp_script), stack="docker")
        content = temp_script.read_text()
        assert "docker --version" in content

    def test_verification_command_python(self, generator, temp_script):
        generator.generate(str(temp_script), stack="python")
        content = temp_script.read_text()
        assert "python3 --version" in content

    def test_verification_command_nodejs(self, generator, temp_script):
        generator.generate(str(temp_script), stack="nodejs")
        content = temp_script.read_text()
        assert "node --version" in content

    def test_verification_command_ollama(self, generator, temp_script):
        generator.generate(str(temp_script), stack="ollama")
        content = temp_script.read_text()
        assert "ollama --version" in content

    # ===== ANSIBLE SPECIFIC =====
    def test_ansible_yaml_header(self, generator, temp_script):
        generator.generate(str(temp_script), stack="docker", format="ansible")
        content = temp_script.read_text()
        assert content.startswith("---")

    def test_ansible_hosts_localhost(self, generator, temp_script):
        generator.generate(str(temp_script), stack="docker", format="ansible")
        content = temp_script.read_text()
        assert "hosts: localhost" in content

    def test_ansible_become(self, generator, temp_script):
        generator.generate(str(temp_script), stack="docker", format="ansible")
        content = temp_script.read_text()
        assert "become: yes" in content

    # ===== MULTI-STACK COVERAGE =====
    @pytest.mark.parametrize("stack", ["docker", "python", "nodejs", "ollama"])
    def test_all_stacks_bash(self, generator, temp_script, stack):
        generator.generate(str(temp_script), stack=stack, format="bash")
        assert temp_script.exists()
        content = temp_script.read_text()
        assert f"Stack: {stack}" in content

    @pytest.mark.parametrize("stack", ["docker", "python", "nodejs", "ollama"])
    def test_all_stacks_ansible(self, generator, temp_script, stack):
        generator.generate(str(temp_script), stack=stack, format="ansible")
        assert temp_script.exists()
        content = temp_script.read_text()
        assert f"Install {stack}" in content


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
