name: macos

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.rs"

jobs:
  build:
    runs-on: "macos-14"
    
    env:
      CARGO_INCREMENTAL: "0"
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      MACOSX_DEPLOYMENT_TARGET: "11.0"

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
      - name: "Compile with sccache"
        uses: mozilla-actions/sccache-action@v0.0.10
      - name: "Cache Rust Dependencies"
        uses: actions/cache@v4
        id: cache-cargo-vendor
        with:
          path: |
            vendor
            .cargo/config
          key: "cargo-deps-${{ hashFiles('**/Cargo.lock') }}"
      - name: "Vendor dependencies"
        if: steps.cache-cargo-vendor.outputs.cache-hit != 'true'
        shell: bash
        run: "cargo vendor --locked --versioned-dirs >> .cargo/config"
      - name: "Install System Deps"
        shell: bash
        run: "env CI=yes PATH=$PATH ./get-deps"
      - name: "Build cx-terminal (Release mode)"
        shell: bash
        run: "cargo build -p cx-terminal --release"
      - name: "Build cx-terminal-gui (Release mode)"
        shell: bash
        run: "cargo build -p cx-terminal-gui --release"
      - name: "Install cargo-nextest from Cargo"
        uses: baptiste0928/cargo-install@v3
        with:
          crate: "cargo-nextest"
          cache-key: "macos"
      - name: "Test"
        shell: bash
        run: "cargo nextest run --all --no-fail-fast"
